export const colors = {
  bg: "#0F1117",
  surface: "#1A1D27",
  surfaceHover: "#222633",
  border: "#2A2E3B",
  borderLight: "#363B4D",
  text: "#E8E9ED",
  textSecondary: "#8B8FA3",
  textMuted: "#5C6078",
  accent: "#3B82F6",
  accentHover: "#2563EB",
  accentSoft: "rgba(59,130,246,0.12)",
  success: "#10B981",
  successSoft: "rgba(16,185,129,0.12)",
  warning: "#F59E0B",
  warningSoft: "rgba(245,158,11,0.12)",
  danger: "#EF4444",
  dangerSoft: "rgba(239,68,68,0.12)",
};

export const s = {
  app: { minHeight: "100vh", background: colors.bg, color: colors.text, fontFamily: "'DM Sans', 'Segoe UI', sans-serif", fontSize: 14 },
  sidebar: { width: 220, background: colors.surface, borderRight: `1px solid ${colors.border}`, padding: "20px 0", display: "flex", flexDirection: "column", position: "fixed", top: 0, left: 0, bottom: 0, zIndex: 10 },
  sidebarLogo: { padding: "0 20px 24px", fontSize: 18, fontWeight: 700, letterSpacing: "-0.02em", color: colors.accent },
  sidebarItem: (active) => ({ padding: "10px 20px", cursor: "pointer", fontSize: 13, fontWeight: active ? 600 : 400, color: active ? colors.text : colors.textSecondary, background: active ? colors.accentSoft : "transparent", borderRight: active ? `2px solid ${colors.accent}` : "2px solid transparent", transition: "all 0.15s" }),
  main: { marginLeft: 220, padding: "24px 32px" },
  pageTitle: { fontSize: 22, fontWeight: 700, letterSpacing: "-0.02em", marginBottom: 4 },
  pageSubtitle: { fontSize: 13, color: colors.textSecondary, marginBottom: 24 },
  card: { background: colors.surface, border: `1px solid ${colors.border}`, borderRadius: 10, padding: 20, marginBottom: 16 },
  cardTitle: { fontSize: 14, fontWeight: 600, marginBottom: 12, display: "flex", alignItems: "center", gap: 8 },
  input: { width: "100%", padding: "9px 12px", background: colors.bg, border: `1px solid ${colors.border}`, borderRadius: 6, color: colors.text, fontSize: 13, outline: "none", boxSizing: "border-box" },
  select: { padding: "9px 12px", background: colors.bg, border: `1px solid ${colors.border}`, borderRadius: 6, color: colors.text, fontSize: 13, outline: "none" },
  btn: (variant = "primary") => ({
    padding: "8px 16px", borderRadius: 6, border: "none", cursor: "pointer", fontSize: 13, fontWeight: 600, transition: "all 0.15s",
    background: variant === "primary" ? colors.accent : variant === "danger" ? colors.danger : "transparent",
    color: variant === "ghost" ? colors.textSecondary : "#fff",
    ...(variant === "ghost" ? { border: `1px solid ${colors.border}` } : {}),
  }),
  badge: (type) => ({
    display: "inline-flex", alignItems: "center", gap: 4, padding: "3px 8px", borderRadius: 4, fontSize: 11, fontWeight: 600,
    background: type === "ok" ? colors.successSoft : type === "attention" ? colors.warningSoft : type === "critique" ? colors.dangerSoft : colors.accentSoft,
    color: type === "ok" ? colors.success : type === "attention" ? colors.warning : type === "critique" ? colors.danger : colors.accent,
  }),
  table: { width: "100%", borderCollapse: "collapse" },
  th: { textAlign: "left", padding: "8px 12px", fontSize: 11, fontWeight: 600, color: colors.textMuted, textTransform: "uppercase", letterSpacing: "0.05em", borderBottom: `1px solid ${colors.border}` },
  td: { padding: "10px 12px", fontSize: 13, borderBottom: `1px solid ${colors.border}` },
  row: { transition: "background 0.1s", cursor: "pointer" },
  statsCard: (color) => ({ background: colors.surface, border: `1px solid ${colors.border}`, borderRadius: 10, padding: "16px 20px", borderLeft: `3px solid ${color}`, flex: 1 }),
  statsValue: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" },
  statsLabel: { fontSize: 11, color: colors.textSecondary, marginTop: 2 },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.6)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 },
  modal: { background: colors.surface, border: `1px solid ${colors.border}`, borderRadius: 12, padding: 24, width: 600, maxHeight: "80vh", overflow: "auto" },
};
